const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');

(async () => {
  const courts = await import(pathToFileURL('PagesCourtIssum/src/lib/courts.js').href);
  const nowMs = Date.parse('2026-09-07T01:00:00Z');
  const date = '20260908';
  const checkedAt = new Date(nowMs).toISOString();
  const slot = { timeContent: '18:00 ~ 20:00' };
  const currentMeta = { query_status: 'success', availability_status: 'available', checked_at: checkedAt };
  const unknown = { title: '가상테니스장(1코트)', reservation_type: 'unknown', application_status: 'unknown' };
  const known = { ...unknown, reservation_type: 'city_priority', application_status: 'open', metadata_checked_at: checkedAt };
  const options = { nowMs };
  const data = { availability_meta: { '12345': { [date]: currentMeta }, 'yongin:12345': { [date]: currentMeta }, 'suwon:1': { [date]: currentMeta } } };
  assert.equal(courts.cityOfFacilityId('12345'), 'yongin');
  assert.equal(courts.slotIsAvailable(data, '12345', date, unknown, slot, options), false, 'legacy numeric Yongin IDs must require verified product metadata too');
  assert.equal(courts.slotIsAvailable(data, '12345', date, known, slot, options), true);
  assert.equal(courts.slotIsAvailable(data, '12345', date, { ...known, metadata_checked_at: '2026-09-05T01:00:00Z' }, slot, options), false);
  assert.equal(courts.slotIsAvailable(data, 'suwon:1', date, unknown, slot, options), true, 'non-Yongin sources can publish verified slots without unsupported product metadata');
  const yonginOnlyMetadata = { ...known, application_status: 'not_open', application_start_date: '20990101', application_end_date: '20000101', use_start_date: '20990101', use_end_date: '20000101' };
  for (const city of courts.CITY_KEYS.filter(city => city !== 'yongin')) {
    const cid = `${city}:1`;
    const cityData = { facilities: { [cid]: yonginOnlyMetadata }, availability: { [cid]: { [date]: [slot] } }, availability_meta: { [cid]: { [date]: currentMeta } } };
    const rows = courts.collectCourtRows(cityData, { city, date, reservationType: 'district_priority', ...options });
    assert.equal(rows.length, 1, `${city} must ignore a Yongin type filter from an old URL`);
    assert.equal(rows[0].count, 1, `${city} must ignore Yongin product metadata`);
    assert.deepEqual(rows[0].reservationTypeLabels, []);
    assert.deepEqual(rows[0].applicationStatusLabels, []);
    assert.equal(rows[0].slots[0].reservationTypeLabel, '');
    assert.deepEqual(courts.buildCourtOptions(cityData, city)[0].reservationTypes, []);
    assert.equal(courts.slotIsAvailable(cityData, cid, date, yonginOnlyMetadata, { ...slot, remaining: 0 }, options), false, `${city} must still reject zero availability`);
    const group = rows[0].courtGroup;
    const favoriteFilters = { city, date, favoritesOnly: true, ...options };
    assert.equal(courts.collectCourtRows(cityData, favoriteFilters).length, 0);
    const saved = new Set([`${city}|${group}`]);
    assert.equal(courts.collectCourtRows(cityData, favoriteFilters, saved).length, 1);
    assert.equal(courts.collectCourtRows(cityData, favoriteFilters, new Set([`yongin|${group}`])).length, 0, 'favorites must be scoped to their city');
    cityData.availability[cid][date] = [];
    cityData.availability_meta[cid][date].availability_status = 'confirmed_empty';
    assert.equal(courts.buildCourtOptions(cityData, city).length, 1, 'sold out courts can still be added to favorites');
    assert.equal(courts.collectCourtRows(cityData, favoriteFilters, saved)[0].favorite, true, 'saved courts remain visible when sold out');
    cityData.availability_meta[cid][date].availability_status = 'available';
  }
  assert.equal(courts.slotIsAvailable(data, 'suwon:1', date, unknown, { timeContent: '18:00 (1회차)' }, options), true, 'Suwon calendar publishes valid start-only time labels');
  assert.equal(courts.slotIsAvailable(data, 'suwon:1', date, unknown, { timeContent: '25:00 (1회차)' }, options), false, 'start-only compatibility must not accept invalid times');
  const failed = { availability_meta: { 'yongin:12345': { [date]: { ...currentMeta, query_status: 'failed', updated_at: checkedAt } } } };
  assert.equal(courts.slotIsAvailable(failed, 'yongin:12345', date, known, slot, options), false, 'recent failed attempt must not resurrect last successful slots');
  const stale = { availability_meta: { 'yongin:12345': { [date]: { ...currentMeta, checked_at: '2026-09-05T01:00:00Z', updated_at: checkedAt } } } };
  assert.equal(courts.slotIsAvailable(stale, 'yongin:12345', date, known, slot, options), false, 'fresh updated_at cannot replace stale successful checked_at');
  console.log('Reservation policy edge tests passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
